#%RAML 1.0 DataType
properties:
            Message:
              type: string
              example:
                "Book Added"
            BookCode:
              type: string
              example:
                "BK444"