#%RAML 1.0 DataType
properties:
        LibraryCode:
          type: string
          example:
            "IBS123"
        tital:
          type: string
          example:
            "Half Girlfriend"
        author:
          type: string
          example:
            "Chetan Bhagat"