#%RAML 1.0 DataType
properties:
  LibraryCode:
    type: string
    required: true
    description: LibraryCode
  LibraryBrach:
    type: string
    required: false
    description: LibraryBrach
example:
  {
    "LibraryCode":"sdfadf",
    "LibraryBrach":"dwsjdvfhkfjs"
  }