#%RAML 1.0 DataType
properties:
  LibrarycodeId:
    type: string
    example:
     "IBS123"
  Address:
    type: string
    example:
      "Hydarabad"
  PhoneNumber:
    type: number
    example:
      9945194646
  Email:
    type: string
    example:
     "Klark@gmail.com"