#%RAML 1.0 Trait
  headers :
   client_id :
      type: string
      description: clinght Id 
   client_secret :
      type: string
      description: client_secret
   X-Corrlation-id:
      type: string
      description: transation Id