http:
 Port: "8081"
 readTimeOut: "30000"
 Path: "/console/*"
 
 DB:
  Host: "bsstdw1cz3g5ptpajna9-mysql.services.clever-cloud.com"
  Port: "3306"
  User: "uhzhkqeenuyurumf"
  Password: "8FHcGywzQFwha9iI0QoS"
  Database: "bsstdw1cz3g5ptpajna9"